trigger:
  - main

pr:
  autoCancel: true


stages:
# MSVC
- stage: MSVC
  dependsOn: []
  jobs:
  - template: ./pipelines/jobs.yml
    parameters:
      jobName: 'Validate MSVC Clang'
      imageName: windows-latest
      CXXVersions: [ 17 ]
      buildTypes: [ 'Release' ]
