parameters:
  jobName: ''
  imageName: ''
  CXXVersions: [ 14, 17, 20 ]
  buildTypes: [ 'Debug', 'Release' ]

jobs:
- ${{ each CXXVersion in parameters.CXXVersions }}:
  - ${{ each buildType in parameters.buildTypes }}:
    - job:
      displayName: ${{ format('{0} {1} C++{2}', parameters.imageName, buildType, CXXVersion) }}
      pool:
        vmImage: ${{ parameters.imageName }}
      continueOnError: false
      steps:
      - template: ./steps.yml
        parameters:
          buildType: ${{ buildType }}
          CXXVersion: ${{ CXXVersion }}
